import type { MultiAgentAgent, MultiAgentRole, MultiAgentScenario, MultiAgentTaskSpec } from './types';

function role(id: string, label: string, description: string): MultiAgentRole {
  return { id, label, description };
}

function task(input: MultiAgentTaskSpec): MultiAgentTaskSpec {
  return input;
}

const supervisorRole = role('supervisor', 'Supervisor', 'Coordinates the overall plan and merges outputs.');
const researchRole = role('researcher', 'Researcher', 'Finds evidence and source material.');
const analystRole = role('analyst', 'Analyst', 'Synthesizes findings into structured insights.');
const writerRole = role('writer', 'Writer', 'Turns findings into polished deliverables.');
const reviewerRole = role('reviewer', 'Reviewer', 'Validates quality, safety, and final correctness.');
const routingRole = role('router', 'Router', 'Passes tasks through a network of agents.');

const baselineAgents: MultiAgentAgent[] = [
  {
    id: 'lead',
    name: 'Lead Coordinator',
    role: supervisorRole,
    capabilities: ['coordination', 'planning', 'aggregation'],
    color: '#f59e0b',
  },
  {
    id: 'research',
    name: 'Research Specialist',
    role: researchRole,
    capabilities: ['research', 'sources', 'analysis'],
    reportsTo: 'lead',
    color: '#38bdf8',
  },
  {
    id: 'analysis',
    name: 'Analysis Specialist',
    role: analystRole,
    capabilities: ['analysis', 'synthesis', 'validation'],
    reportsTo: 'lead',
    color: '#a78bfa',
  },
  {
    id: 'writer',
    name: 'Writer',
    role: writerRole,
    capabilities: ['draft', 'synthesis', 'editing'],
    reportsTo: 'lead',
    color: '#34d399',
  },
  {
    id: 'review',
    name: 'Review Specialist',
    role: reviewerRole,
    capabilities: ['review', 'validation', 'quality'],
    reportsTo: 'lead',
    color: '#fb7185',
  },
];

const networkAgents: MultiAgentAgent[] = [
  {
    id: 'lead',
    name: 'Network Coordinator',
    role: supervisorRole,
    capabilities: ['coordination', 'aggregation'],
    color: '#f59e0b',
  },
  {
    id: 'router-a',
    name: 'Router Alpha',
    role: routingRole,
    capabilities: ['routing', 'analysis', 'handoff'],
    reportsTo: 'lead',
    color: '#60a5fa',
  },
  {
    id: 'router-b',
    name: 'Router Beta',
    role: routingRole,
    capabilities: ['routing', 'review', 'handoff'],
    reportsTo: 'lead',
    color: '#22d3ee',
  },
  {
    id: 'synth',
    name: 'Synthesis Node',
    role: analystRole,
    capabilities: ['analysis', 'synthesis', 'draft'],
    reportsTo: 'lead',
    color: '#a78bfa',
  },
];

export const supervisorScenario: MultiAgentScenario = {
  id: 'supervisor-briefing',
  name: 'Supervisor Briefing Loop',
  description: 'A lead agent fans out research, synthesis, drafting, and review before final aggregation.',
  pattern: 'supervisor',
  agents: baselineAgents,
  rootTask: task({
    id: 'brief-root',
    title: 'Produce a launch brief for the AI Learning Playground',
    description: 'Coordinate the end-to-end brief and aggregate specialist outputs.',
    kind: 'coordination',
    effort: 3,
    requiredCapabilities: ['coordination'],
    preferredAgentId: 'lead',
  }),
  tasks: [
    task({
      id: 'brief-research',
      title: 'Collect standout product references',
      description: 'Gather visual and learning-design references for premium playground experiences.',
      kind: 'research',
      effort: 2,
      requiredCapabilities: ['research'],
      preferredAgentId: 'research',
      parentTaskId: 'brief-root',
      dependsOn: ['brief-root'],
    }),
    task({
      id: 'brief-analysis',
      title: 'Extract reusable experience principles',
      description: 'Distill the research into concrete interaction and pedagogy principles.',
      kind: 'analysis',
      effort: 2,
      requiredCapabilities: ['analysis'],
      preferredAgentId: 'analysis',
      parentTaskId: 'brief-root',
      dependsOn: ['brief-research'],
    }),
    task({
      id: 'brief-draft',
      title: 'Draft the standout-experience brief',
      description: 'Write the recommendation memo for the new cockpit ecosystem.',
      kind: 'draft',
      effort: 3,
      requiredCapabilities: ['draft'],
      preferredAgentId: 'writer',
      parentTaskId: 'brief-root',
      dependsOn: ['brief-analysis'],
    }),
    task({
      id: 'brief-review',
      title: 'Review risk and delivery readiness',
      description: 'Check for feasibility, testability, and product coherence gaps.',
      kind: 'review',
      effort: 2,
      requiredCapabilities: ['review'],
      preferredAgentId: 'review',
      parentTaskId: 'brief-root',
      dependsOn: ['brief-draft'],
    }),
  ],
};

export const sequentialScenario: MultiAgentScenario = {
  id: 'sequential-decision-memo',
  name: 'Sequential Decision Memo',
  description: 'A baton-pass workflow where each specialist waits for the prior stage to complete.',
  pattern: 'sequential',
  agents: baselineAgents,
  rootTask: task({
    id: 'memo-root',
    title: 'Prepare a decision memo for the next cockpit tranche',
    description: 'Orchestrate a serialized memo workflow.',
    kind: 'coordination',
    effort: 2,
    requiredCapabilities: ['coordination'],
    preferredAgentId: 'lead',
  }),
  tasks: [
    task({
      id: 'memo-research',
      title: 'Research comparable learning products',
      description: 'Identify comparable products and summarize their strongest mechanics.',
      kind: 'research',
      effort: 2,
      requiredCapabilities: ['research'],
      dependsOn: ['memo-root'],
      parentTaskId: 'memo-root',
    }),
    task({
      id: 'memo-analysis',
      title: 'Analyze tradeoffs',
      description: 'Turn product research into a recommendation frame.',
      kind: 'analysis',
      effort: 2,
      requiredCapabilities: ['analysis'],
      dependsOn: ['memo-research'],
      parentTaskId: 'memo-root',
    }),
    task({
      id: 'memo-draft',
      title: 'Draft the decision memo',
      description: 'Write the recommendation and rationale.',
      kind: 'draft',
      effort: 2,
      requiredCapabilities: ['draft'],
      dependsOn: ['memo-analysis'],
      parentTaskId: 'memo-root',
    }),
    task({
      id: 'memo-validate',
      title: 'Validate assumptions',
      description: 'Check claims and edge cases before circulation.',
      kind: 'validation',
      effort: 1,
      requiredCapabilities: ['validation'],
      dependsOn: ['memo-draft'],
      parentTaskId: 'memo-root',
    }),
  ],
};

export const parallelScenario: MultiAgentScenario = {
  id: 'parallel-signal-scan',
  name: 'Parallel Signal Scan',
  description: 'Multiple specialists branch out in the same wave before the lead merges the outcomes.',
  pattern: 'parallel',
  agents: baselineAgents,
  rootTask: task({
    id: 'parallel-root',
    title: 'Scan the market for cockpit inspiration',
    description: 'Coordinate simultaneous research and aggregate the strongest opportunities.',
    kind: 'coordination',
    effort: 2,
    requiredCapabilities: ['coordination'],
    preferredAgentId: 'lead',
  }),
  tasks: [
    task({
      id: 'scan-market',
      title: 'Scan market references',
      description: 'Review category leaders and direct competitors.',
      kind: 'research',
      effort: 2,
      requiredCapabilities: ['research'],
      parentTaskId: 'parallel-root',
      dependsOn: ['parallel-root'],
      wave: 1,
    }),
    task({
      id: 'scan-tech',
      title: 'Scan technical interaction patterns',
      description: 'Review protocol visualizers and simulation interfaces.',
      kind: 'analysis',
      effort: 2,
      requiredCapabilities: ['analysis'],
      parentTaskId: 'parallel-root',
      dependsOn: ['parallel-root'],
      wave: 1,
    }),
    task({
      id: 'scan-ux',
      title: 'Scan onboarding patterns',
      description: 'Find the fastest paths to first insight for new users.',
      kind: 'research',
      effort: 2,
      requiredCapabilities: ['research'],
      parentTaskId: 'parallel-root',
      dependsOn: ['parallel-root'],
      wave: 1,
    }),
    task({
      id: 'scan-synthesis',
      title: 'Synthesize shared principles',
      description: 'Turn the three scans into an actionable shortlist.',
      kind: 'synthesis',
      effort: 3,
      requiredCapabilities: ['synthesis'],
      preferredAgentId: 'writer',
      parentTaskId: 'parallel-root',
      dependsOn: ['scan-market', 'scan-tech', 'scan-ux'],
      wave: 2,
    }),
  ],
};

export const networkScenario: MultiAgentScenario = {
  id: 'network-routing-demo',
  name: 'Network Routing Demo',
  description: 'Tasks travel through a mesh of agents before reaching the final synthesis node.',
  pattern: 'network',
  agents: networkAgents,
  rootTask: task({
    id: 'network-root',
    title: 'Route a protocol incident across a mesh',
    description: 'Coordinate a multi-hop investigation and final recommendation.',
    kind: 'coordination',
    effort: 2,
    requiredCapabilities: ['coordination'],
    preferredAgentId: 'lead',
  }),
  tasks: [
    task({
      id: 'network-observe',
      title: 'Observe the incoming protocol stream',
      description: 'Collect initial telemetry from the mesh.',
      kind: 'analysis',
      effort: 1,
      requiredCapabilities: ['analysis'],
      parentTaskId: 'network-root',
      dependsOn: ['network-root'],
      routeThrough: ['lead', 'router-a', 'synth'],
    }),
    task({
      id: 'network-verify',
      title: 'Verify the anomaly through a second path',
      description: 'Route verification through an alternate node.',
      kind: 'validation',
      effort: 2,
      requiredCapabilities: ['review'],
      parentTaskId: 'network-root',
      dependsOn: ['network-observe'],
      routeThrough: ['lead', 'router-b', 'synth'],
    }),
    task({
      id: 'network-recommend',
      title: 'Recommend the next orchestration move',
      description: 'Turn routed evidence into a decision for the coordinator.',
      kind: 'synthesis',
      effort: 2,
      requiredCapabilities: ['synthesis'],
      parentTaskId: 'network-root',
      dependsOn: ['network-verify'],
      routeThrough: ['router-a', 'router-b', 'synth'],
    }),
  ],
};

export const dispatchTreeScenario: MultiAgentScenario = {
  id: 'dispatch-tree-review',
  name: 'Dispatch Tree Review',
  description: 'A deep parent/child tree that shows recursive delegation and nested aggregation.',
  pattern: 'dispatch-tree',
  agents: baselineAgents,
  rootTask: task({
    id: 'dispatch-root',
    title: 'Review a product launch plan with recursive delegation',
    description: 'Create a parent task that spawns nested validation branches.',
    kind: 'dispatch',
    effort: 3,
    requiredCapabilities: ['coordination'],
    preferredAgentId: 'lead',
  }),
  tasks: [
    task({
      id: 'dispatch-research',
      title: 'Gather supporting evidence',
      description: 'Collect source material before deeper checks begin.',
      kind: 'research',
      effort: 2,
      requiredCapabilities: ['research'],
      parentTaskId: 'dispatch-root',
      dependsOn: ['dispatch-root'],
    }),
    task({
      id: 'dispatch-security',
      title: 'Run safety validation',
      description: 'Inspect risk and compliance assumptions.',
      kind: 'validation',
      effort: 2,
      requiredCapabilities: ['validation'],
      parentTaskId: 'dispatch-research',
      dependsOn: ['dispatch-research'],
    }),
    task({
      id: 'dispatch-security-followup',
      title: 'Confirm flagged risks',
      description: 'Perform a deeper follow-up validation on the most sensitive issues.',
      kind: 'review',
      effort: 1,
      requiredCapabilities: ['review'],
      parentTaskId: 'dispatch-security',
      dependsOn: ['dispatch-security'],
    }),
    task({
      id: 'dispatch-quality',
      title: 'Check experience quality',
      description: 'Inspect UX and communication quality for the launch plan.',
      kind: 'review',
      effort: 2,
      requiredCapabilities: ['review'],
      parentTaskId: 'dispatch-research',
      dependsOn: ['dispatch-research'],
    }),
    task({
      id: 'dispatch-summary',
      title: 'Prepare the final merged review',
      description: 'Roll nested validations back up into one recommendation.',
      kind: 'synthesis',
      effort: 3,
      requiredCapabilities: ['synthesis'],
      parentTaskId: 'dispatch-root',
      dependsOn: ['dispatch-security-followup', 'dispatch-quality'],
    }),
  ],
};

export const ALL_MULTI_AGENT_SCENARIOS: MultiAgentScenario[] = [
  supervisorScenario,
  sequentialScenario,
  parallelScenario,
  networkScenario,
  dispatchTreeScenario,
];
